forge 'https://forgeapi.puppetlabs.com'

mod 'puppetlabs-apache', '1.10.0'
mod 'puppetlabs-motd', '1.4.0'
mod 'puppetlabs-ntp', '4.2.0'
mod 'puppetlabs-stdlib', '4.12.0'
mod 'elasticsearch-elasticsearch', '0.14.0'

