forge 'https://forgeapi.puppetlabs.com'

mod 'puppetlabs-apache', '1.10.0'
mod 'puppetlabs-motd', '1.4.0'
mod 'puppetlabs-ntp', '4.2.0'
mod 'puppetlabs-stdlib', '4.13.0'
mod 'elastic-elasticsearch', '5.2.0'

